### ISSUE TITLE
How to create new annotation/label for a new image

### ISSUE THREAD

**Issue by TrianzAIM** [bit-bots/imagetagger#102]
Hi

I would like to annotate a region of the car that was damaged, how to do this? In the web view its asking to select ball ,goal etc which are not from this image.

https://imagetagger.bit-bots.de/annotations/228858/

Regards,
Sri Nivas

**Comment by NFiedler** [comment]
Only admins are able to add annotation types to an ImageTagger instance. As I explained in #95, we want to keep the number of types low. The public instance which you are using currently is for RoboCup and demo purposes only.
If you want to label your custom categories, you need to host your own ImageTagger instance. (We could host an instance for you, contact me by [mail](mailto:git@nfiedler.de).)

**Comment by sharedcare** [comment]
I host an ImageTagger instance on my own server. How can I create new main annotation types?

**Comment by NFiedler** [comment]
You log in as an administrator user and then you will find an "Administration" link in the footer. The menu there allows you to create new annotation types. I hope this helps. Feel free to ask further questions. :)

Happy tagging, 
Niklas
