### ISSUE TITLE
Annotation for Penalty Cross

### ISSUE THREAD

**Issue by Geekiens** [bit-bots/imagetagger#104]
Hi, we would like to add another annotation type to our images. Currently we can't annotate the penalty cross.
As we read in #102 only admin are able to add new types.

We suggest a rectangle bounding box like in this picture:
![image](https://user-images.githubusercontent.com/16350263/48208856-0e464d80-e374-11e8-8709-727084d29019.png)

Regards,
Max Brämer

**Comment by NFiedler** [comment]
I added the option. Happy tagging :)
