### ISSUE TITLE
upload tool?

### ISSUE THREAD

**Issue by stvogel** [bit-bots/imagetagger#106]
What's this entry about? What tools can I upload here?
Is it possible to extend imagetagger?
And if ... how is this done?

**Comment by NFiedler** [comment]
It just adds a possibility to upload and distribute scripts via the platform itself. In the RoboCup context, we use it to distribute tools for further processing of the labels (like creating ROS-Bags from labels). Those tools are context specific but multiple teams in an ImageTagger instance could profit from them. It is not a Plug-In system or something like that. 
If you require a new feature, feel free to open an issue with a feature request or open a pull request. For further questions feel free to ask them here or contact me via [mail](mailto:git@nfiedler.de).

**Comment by stvogel** [comment]
Thanks, @NFiedler for the info.
In fact I really thought it would be some kind of plugin system.
