### ISSUE TITLE
How do you add new meta annotation types like Blurred and Concealed?

### ISSUE THREAD

**Issue by JustinMBrown** [bit-bots/imagetagger#118]
I have the django project opened, and I'm trying to add more meta annotation types, but there are a ton of places in code that need updating just to add a single new type. Is there an easy way to do this using some configuration file, or are these fields really just hard coded values that require many changes through the code?

**Comment by ftsell** [comment]
As far as I know you would have to do it manually in a lot of code places. And don't forget the JavaScript files.

What meta-type are you looking for? It might be worth it to implement it in general

**Comment by JustinMBrown** [comment]
That's what I ended up doing, it wasn't too hard. Actually, I specifically ended up converting concealed and blurred into integer values that ranged from 0 to 5 to denote the magnitude of occlusion and blurriness.
