### ISSUE TITLE
registering new users seems to be broken at the moment

### ISSUE THREAD

**Issue by roboeireann** [bit-bots/imagetagger#130]
Registering a new user on the imagetagger website results in a long error message which starts with:

Request Method: | POST
-- | --
https://imagetagger.bit-bots.de/accounts/register/
2.0.13
ConnectionRefusedError
[Errno 111] Connection refused
/usr/lib/python3.7/socket.py in create_connection, line 716
/usr/local/bin/uwsgi
3.7.3
['.',  '',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/src/django-registration',  '/usr/lib/python3/dist-packages']
Thu, 12 Dec 2019 14:59:21 +0000

and ends with

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by NFiedler** [comment]
I can reproduce this. Thank you for reporting this. @timonegk is on it.

**Comment by timonegk** [comment]
Thank you for reporting the problem. We had an issue with the mail server connection since we recently changed some deployment infrastructure. Registration should now work as expected and your previous unsuccessful registration attempts have been cleared. Please try again.
