### ISSUE TITLE
Internal Server Error (500) on create imageset

### ISSUE THREAD

**Issue by wrigsa** [bit-bots/imagetagger#142]
When I try to create an image set, upon clicking create I get redirected to an error page. I can create new teams and users, just not image sets. I made sure the UPLOAD_FS_GROUP matches the id of the group that I'm in. Do you know what could be causing this issue? Thanks

**Comment by timonegk** [comment]
In the exception log of your HTTP server or when DEBUG is set to True in settings.py, you should see a backtrace containing further information about the problem. If you feel unable to solve them yourself, feel free to provide us with the backtrace to allow further debugging.

**Comment by wrigsa** [comment]
It was a little silly. I just needed to run the server with admin privileges
