### ISSUE TITLE
Cant export Annotation

### ISSUE THREAD

**Issue by BenjiSchlotter** [bit-bots/imagetagger#153]
## Expected behavior
I want to export Annotations for https://imagetagger.bit-bots.de/images/imageset/835/ because it is a Dataset used in the RoboCup Brazil Robot Detection Challenge. I can create a new format but the i am unable to export it or any other format. I can only download existing exports.

## Current behavior
Internal Server Error (500)
We're sorry, but we didn't expect this to happen. Our error reporting tool should have sent an email to us with some technical details. Please try again later. If the problem persists, see our problem reporting page.

We have recorded the error under the Identifier 98d54a6181b6440c834d406ae9e89aa5.

## Steps to Reproduce
1. got to https://imagetagger.bit-bots.de/images/imageset/835/
2. click on export
3. Look at internal server error in frustration ;)

### Where does the issue occur?

- [ ] Self hosted instance
- [x] Public instance (https://imagetagger.bit-bots.de)

**Comment by timonegk** [comment]
Hi, I am sorry for the inconvenience. The problem was that the team owning the image set has been deleted. I opened a pull request and we should get it merged and deployed today.

**Comment by timonegk** [comment]
By the way, how did you learn about the Brazil Open this year? We only heard about it on the robocup-worldwide mailing list when the registration deadline had already passed.

**Comment by BenjiSchlotter** [comment]
@timonegk we did hear about it too late as well. But asked if we can still join. If you ask it might be still possible for you.

**Comment by ftsell** [comment]
@BenjiSchlotter The fix has been deployed and you should be able to export your data now.

**Comment by timonegk** [comment]
> @timonegk we did hear about it too late as well. But asked if we can still join. If you ask it might be still possible for you.

Okay, we also asked them as soon as we heard about it but did not receive a reply.
