### ISSUE TITLE
Nginx blocks upload of large files of annotations

### ISSUE THREAD

**Issue by jaagut** [bit-bots/imagetagger#162]
## Expected behavior
Able to upload large files of annotations

## Current behavior
Blocks upload for files of annotations for ~4000 images

## Steps to Reproduce
1. Ask @Flova 
2.
3.
...

### Where does the issue occur?

- [ ] Self hosted instance
- [x] Public instance (https://imagetagger.bit-bots.de)

**Comment by Flova** [comment]
![image](https://user-images.githubusercontent.com/15075613/101258083-55a09300-3720-11eb-8bdd-ecc5289f8818.png)
Label count in the file: 3366

**Comment by jaagut** [comment]
What's the size of the file?

**Comment by timonegk** [comment]
I increased the limit to 4 GB.
