### ISSUE TITLE
Verification view: Handle every annotation of same type of image

### ISSUE THREAD

**Issue by jaagut** [bit-bots/imagetagger#164]
## Is your feature request related to a problem? Please describe.
During verification phase, it's hard to keep track, if for example every goal post visible in the image is labeled.

## Describe the solution you'd like
Add mode to show and verify or deny every annotation of the same type of the current image.

**Comment by Flova** [comment]
I think that is related to the feature request where jonas wanted a combined view to verify all labels of one class in an image.

**Comment by timonegk** [comment]
Yes, this is the issue for that feature.

**Comment by Flova** [comment]
Ah nvm
