### ISSUE TITLE
Simple (mobile) verification view

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/imagetagger#18]
Team Rhoban has a very simple verification view, on which the user only has to select the images containing balls. This has the advantage that they can give it to any person and this person can do the job without prior knowledge. Furthermore this is also simple to do on a mobile device, e.g. smart phone.
A very simple verification view which shows only the area around the label together with the label and a yes/no button would be good. This would then also be possible to run on a mobile platform.

**Comment by timonegk** [comment]
A simple mobile verification view was added in 046611b63a8a98742103de474c174bf22797d7f6. It resembles the large screen verification view, however the image is displayed above the buttons and the edit button is not shown.
