### ISSUE TITLE
Delete account on https://imagetagger.bit-bots.de/

### ISSUE THREAD

**Issue by antedesk** [bit-bots/imagetagger#193]
## What I'm trying to do
Delete my own account from the public instance.

## What I've tried
I went to my profile looking for a `Delete account` section or something similar

### Where does the issue occur?

- [ ] Self-Hosted instance
- [X] Public instance (https://imagetagger.bit-bots.de)

**Comment by jaagut** [comment]
PING @timonegk  @ftsell @NFiedler 
Is this case already resolved? Do we want to implement a button in the future.

**Comment by timonegk** [comment]
I added a button to the profile view in the ImageTagger where you can delete your account.
