### ISSUE TITLE
Docker build and deployment

### ISSUE THREAD

**Issue by EKivutha** [bit-bots/imagetagger#210]
## What I'm trying to do
build a docker image to host on heroku

## What I've tried
changing the prefix for the required env variable to start with the IT_ prefix

## Additional context
I'm getting errors for each variable in the base class

If I add the prefix IT_ to the env variables stated in readme, the error message `variable IT_ALLOWED_HOST is required to be set to IT_IT_ALLOWED_HOST`
### Where does the issue occur?

- [ ] Self-Hosted instance

### If it is a self hosted instance, please provide further information

- Operating System: Docker Linux
- Python version:3.8
- UWSGI version:2.0
- ImageTagger commit or version:v0.6
- Further setup information or configuration files
![Screenshot from 2022-02-26 20-27-50](https://user-images.githubusercontent.com/30912874/155853034-c2c33e45-dc05-4a38-84f2-3c7328fc0729.png)

**Comment by timonegk** [comment]
Which command do you run to get the output in your screenshot?

**Comment by EKivutha** [comment]
Sudo docker run -it port 8080 --name imagetagger immagetagger

**Comment by timonegk** [comment]
For all the configuration values, you have to pass them as environment variables, for docker that is with the `-e` flag. So you will have your docker run command with `-e IT_EMAIL_HOST=... -e IT_DB_HOST=...` and so on.

**Comment by EKivutha** [comment]
Do you have a sample terminal code I can run

**Comment by EKivutha** [comment]
> For all the configuration values, you have to pass them as environment variables, for docker that is with the `-e` flag. So you will have your docker run command with `-e IT_EMAIL_HOST=... -e IT_DB_HOST=...` and so on. 

I have tried this but I get a invalid reference format error

**Comment by EKivutha** [comment]
@timonegk  do you have any other deployment materials or documentation?

**Comment by EKivutha** [comment]
issue was not resolved

**Comment by timonegk** [comment]
When working with open source / community projects, please keep in mind that everybody is doing it on their free time. That also means that you have to wait sometimes to get an answer. Pointlessly asking and re-asking and passive-aggressively closing an issue is not a nice way of getting other people's attention.
I sent you a short example of how to add environment variables to your docker container. What exactly did you run to get the "invalid reference format" error? Of course, you cannot let the values at `...` but have to add an actually useful value.
Maybe check out the corresponding section of the README: https://github.com/bit-bots/imagetagger/#minimal-production-configuration. There are the five environment variables that have to be defined for the imagetagger to run. For it to work, you have to have installed and started a postgresql server. If you haven't done that yet, there are countless tutorials online.
