### ISSUE TITLE
Question about "Annotate the whole set"

### ISSUE THREAD

**Issue by robbine** [bit-bots/imagetagger#214]
I'm try to annotate a new dataset which contains army images, and have two annotation types, namly 'soldier' and 'gun'.
Do I need to first select 'soldier' from dropdown box of 'Not in image annotation type' to annotate all images once.
And then select 'gun' from dropdown box to annotate all over again ?
 Moreover, how to create negative dataset quickly by doing this ?

**Comment by NFiedler** [comment]
We neither endorse nor support military usage.
