### ISSUE TITLE
having "not in image" and "keep selection" both selected leads to following annotations not loading

### ISSUE THREAD

**Issue by johagge** [bit-bots/imagetagger#24]
When you have the checkbox for "not in the image" and "keep selection for next" checked at the same time, the existing annotations below the pictures will be stuck on "Loading...". 
They will load again after reloading the page or unselecting "keep selection for next" and loading the next image.
Not in image also does not keep selected, even though it seems like it should with keep selection.

**Comment by NFiedler** [comment]
692363a should fix the issue.
