### ISSUE TITLE
Preloading images for faster tagging

### ISSUE THREAD

**Issue by MrSunday334** [bit-bots/imagetagger#3]
As tagging is for itself very fast, the loading time for the image is relatively long. It would be nice to preload images, so that when going to the next page the image is already in the browser cache.

Loading the image of the next page with javascript or in a hidden object should do this.

**Comment by NFiedler** [comment]
the preloading is implemented for the tagging view, but still missing for verifications

**Comment by Daniel451** [comment]
Image preloading for tagging is already implemented.
Related to [Image preloading for verification view #33](https://github.com/bit-bots/imagetagger/issues/33).
