### ISSUE TITLE
Dataset right managment

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/imagetagger#30]
Some teams seem to be interested in having the possibility to forbid other from changing labels, thus making some sort of "read only" datasets.
This would need some sort of rights management for datasets. Probably, just an option for everybody can change/add labels and only team members can do it, is enough.

**Comment by NFiedler** [comment]
aee4825a73110ab499cd88c64c163846aaebc90e and some earlier commits should implement the desired feature. Now public means 'read only' while public and public collaboration enable read and write permissions for public users. Some blockades are implemented rather ugly, but #43 should fix that.
