### ISSUE TITLE
"Concealed" as annotation attribute

### ISSUE THREAD

**Issue by timonegk** [bit-bots/imagetagger#36]
"Concealed" should be an annotation attribute with a checkbox (like "not in image"). 
This would permit users to 
- filter for annotations like "ball" and concealed balls would also be filtered
- annotate concealed balls easier

When adding new annotation types, the "concealed" checkbox should be optional.

**Comment by Daniel451** [comment]
Good idea. What do you think @NFiedler?
It is also easier to read labels this way --> if you do not care for concealed attribute, one could just ignore it. If one does care, special treatment in could be implemented in a parser.
Currently one would have to read in different labels exports.

**Comment by NFiedler** [comment]
I already started to implement the feature. It's quite complex and a lot of small adaptations and tests are necessary. So it'll take some time. And i will implement it step by step:
* Labeling
* Editing
* Exports
* Validation

**Comment by NFiedler** [comment]
Additionally to "concealed", "blurred" would be useful, too.

**Comment by jgueldenstein** [comment]
I support this very much, filtering is very hard with concealed and non concealed balls

**Comment by NFiedler** [comment]
Implemented it with c73ea494d4dd617705faa31489a3f2f03f07ef1f
