### ISSUE TITLE
label export filter not working properly

### ISSUE THREAD

**Issue by Daniel451** [bit-bots/imagetagger#39]
Exporting labels in (for example) "AI Ball" format should **only** include ball labels, nothing else. However, some exports showed goalpost "filename|not_in_image" labels in the export.txt. Tested on two different imagesets now and also re-created the exports -> same behavior.

Most likely the labels are not filtered correctly. Maybe it is just "not_in_image" labels that are not filtered.

Fix should have high priority imho, since this highly affects the usability of exports.

**Comment by NFiedler** [comment]
This issue consisted of two separate bugs. We did not save the annotations_type of an export format at all. It looked like it worked because there was no annotation type filtering in the export creation at all.
Now i fixed these issues, meaning that export formats can break.
