### ISSUE TITLE
Tags/labels for datasets

### ISSUE THREAD

**Issue by Daniel451** [bit-bots/imagetagger#49]
For ease of use with a high number of datasets we need a fast & simple method to sort & filter datasets. One convenient way would be the implementation of tags/labels for datasets like GitHub for example does with issues. This way admins could create labels and each dataset could be assigned with any number of labels, like "ball", "nagoya", "2017", "eu-ball", "test-set". In order to easily identify labels they should at least have colors (like in GitHub) or even small icons.

**Comment by NFiedler** [comment]
I'm not sure about the scope of the labels. Are they created by every team or globally? In GitHub the labels are labels are bound to a single repository with multiple issues. I think binding them to a team with multiple image sets is the fitting analogy.

**Comment by NFiedler** [comment]
And maybe it would be less confusing calling them topics. Labels, tags and annotations are used already to refer to... labels. Or however we call them.

**Comment by NFiedler** [comment]
We started to work on the issue. Tags will be called "Tags" and they will be global to improve the collaboration between teams. The option to define a tag-color will not get implemented at the beginning. An autocomplete feature will help to stick to existing tags. Everyone can create new ones. An imageset can have multiple tags.

**Comment by NFiedler** [comment]
With fff9efa4b8d4fafbee74717ff6ce7395bb46ae51 and preceding commits, we added the option to tag imagesets with autocompletion for tag names, search for tag(s) in the explore view and each tag links to the search for imagesets with that tag.
