### ISSUE TITLE
Select annotations and recolor/redye their bounding-box

### ISSUE THREAD

**Issue by JanGut** [bit-bots/imagetagger#63]
Select annotations in annotation list, then change color of their bounding-box in imageview.
This is usefull to differentiate between multiple annotations e.g to delete annotations.

**Comment by Daniel451** [comment]
I would suggest to at least have the option to define custom colors for each annotation type.

**Comment by timonegk** [comment]
As of cf2eaac87c4353c41c40afae1af8ca1057c4e1aa, it is possible to select an annotation by clicking on the annotation in the annotation list. @Daniel451 there is now a separate issue for that (#73).
