### ISSUE TITLE
Download script does not support special characters in passwords

### ISSUE THREAD

**Issue by bpoppinga** [bit-bots/imagetagger#64]
Login failed, even though the username and password are right

**Comment by NFiedler** [comment]
I tried to reproduce the error, but it works for me. Can you give a bit more information on how you use it (instance, imageset id, username if it is on [imagetagger.bit-bots.de](http://imagetagger.bit-bots.de))? Are you sure, that you have the needed access rights on the set you want to download?

**Comment by NFiedler** [comment]
After further diagnosis we discovered that the download script does not support special characters in passwords.

**Comment by johagge** [comment]
special characters in passwords are now supported through the new download script  (3002ec90fc12ef6711f2b49bee1b1a6ae9e90c6b and following)
