### ISSUE TITLE
Add noscript tag

### ISSUE THREAD

**Issue by ftsell** [bit-bots/imagetagger#81]
When you disable Javascript or your Browser does not support it (:laughing:) a lot of the Bootstrap stuff does not seem to work.
For example the My Teams Header does nothing when clicked without Javascript enabled.

You could add a simple noscript tag which asks the user to enable JS or use a better Browser.

**Comment by Daniel451** [comment]
> (...) or use a ~~better~~...

...*more feature-rich* browser :D

**Comment by NFiedler** [comment]
The Bootstrap stuff is the smallest problem, as the annotation and verification view heavily rely on JavaScript.
