### ISSUE TITLE
"This File is unsupported" Error

### ISSUE THREAD

**Issue by sebhoos** [bit-bots/imagetagger#93]
We are receiving a "This file type is unsupported!" error when we try to upload new images generated by our Framework. Our Framework extends an laBl chunk in the .png where we save some information decoded as serialized protobuf string. It's a newer error because we uploaded images containing these extensions before. This error occurs also when we reupload our own images.
A local test of `imghdr.what("filePath")` returns true for our files.

You can find some example images here: NaoDevils/CloseRobots_1_6_18_Loki_1

**Comment by NFiedler** [comment]
This issue was a problem in our settings.py. 
We had file name endings like ".png" in the allowed extensions. With the new method, we don't have the dot in the comparison, so the problem was solved by changing it to "png".
