### ISSUE TITLE
Bad Request (400) when verifying annotations

### ISSUE THREAD

**Issue by mats-claassen** [bit-bots/imagetagger#96]
When I want to verify an annotation I get an error: 400 Bad Request.

Looking at the code in `api_verify_annotation` there seems to be a `KeyError` because "concealed" and "blurred" are not in `request.data`.

My `request.data` looks like this: `{'annotation_id': 4, 'state': 'accept'}`

**Comment by timonegk** [comment]
Indeed, a deprecated API was used on the server side. The error was fixed in 74316a2f4b484d1ba413d2ffe3bc0103e334534f.
