### ISSUE TITLE
view_imageset is requesting invalid url via ajax

### ISSUE THREAD

**Issue by Akasch** [bit-bots/imagetagger#98]
A request for https://imagetagger.bit-bots.de/images/imageset/258/[object Object] is made then opening the view_imageset view. It gets a 404 back, but I think something is broken there in the javascript.

**Comment by timonegk** [comment]
This happened due to the inclusion of the jQuery file upload scripts when the image set was not editable and no upload form was shown. The problem has been fixed in bd4192118ad0bcc7cd21ddf304c2702c63e99374.
